import { NextRequest, NextResponse } from 'next/server';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import path from 'path';

const execAsync = promisify(exec);

interface InstallRequest {
  userInfo: {
    name: string;
    email: string;
    timezone: string;
    language: string;
  };
  mediaPaths: {
    primary: string;
    downloads: string;
    additional: string[];
  };
  apiKeys: {
    tmdb: string;
    opensubtitles: string;
    opensubtitlesUsername: string;
    opensubtitlesPassword: string;
    youtube: string;
  };
  systemConfig: {
    enableRedis: boolean;
    enableTorrents: boolean;
    enableSubtitles: boolean;
    hardwareAcceleration: string;
    maxConcurrentScans: number;
    cacheSize: number;
  };
}

export async function POST(request: NextRequest) {
  try {
    const config: InstallRequest = await request.json();
    
    // Create configuration files
    await createConfigFiles(config);
    
    // Create environment file
    await createEnvironmentFile(config);
    
    // Build and start Docker containers
    await buildAndStartContainers(config);
    
    // Initialize database
    await initializeDatabase(config);
    
    // Verify installation
    await verifyInstallation();
    
    return NextResponse.json({ 
      success: true, 
      message: 'HomeFlix installed successfully' 
    });
  } catch (error) {
    console.error('Installation error:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: error instanceof Error ? error.message : 'Installation failed' 
      },
      { status: 500 }
    );
  }
}

async function createConfigFiles(config: InstallRequest) {
  const configDir = '/app/config';
  
  // Ensure config directory exists
  await fs.mkdir(configDir, { recursive: true });
  
  // Create user config
  const userConfig = {
    name: config.userInfo.name,
    email: config.userInfo.email,
    timezone: config.userInfo.timezone,
    language: config.userInfo.language,
    setupDate: new Date().toISOString()
  };
  
  await fs.writeFile(
    path.join(configDir, 'user.json'),
    JSON.stringify(userConfig, null, 2)
  );
  
  // Create media paths config
  const mediaConfig = {
    paths: [
      {
        path: config.mediaPaths.primary,
        name: 'Primary Media Directory',
        type: 'primary',
        active: true,
        priority: 100
      },
      {
        path: config.mediaPaths.downloads,
        name: 'Downloads Directory',
        type: 'downloads',
        active: true,
        priority: 50
      },
      ...config.mediaPaths.additional.map((path, index) => ({
        path,
        name: `Additional Path ${index + 1}`,
        type: 'additional',
        active: true,
        priority: 25
      }))
    ]
  };
  
  await fs.writeFile(
    path.join(configDir, 'media-paths.json'),
    JSON.stringify(mediaConfig, null, 2)
  );
  
  // Create system config
  const systemConfig = {
    features: {
      redis: config.systemConfig.enableRedis,
      torrents: config.systemConfig.enableTorrents,
      subtitles: config.systemConfig.enableSubtitles
    },
    performance: {
      hardwareAcceleration: config.systemConfig.hardwareAcceleration,
      maxConcurrentScans: config.systemConfig.maxConcurrentScans,
      cacheSize: config.systemConfig.cacheSize
    },
    version: '3.0.0',
    setupComplete: false
  };
  
  await fs.writeFile(
    path.join(configDir, 'system.json'),
    JSON.stringify(systemConfig, null, 2)
  );
}

async function createEnvironmentFile(config: InstallRequest) {
  // Create backend .env file
  const backendEnvContent = [
    '# HomeFlix Backend Configuration',
    '# Generated by Setup Wizard',
    '',
    '# Database Configuration',
    'DATABASE_URL=/app/homeflix.db',
    '',
    '# Server Configuration',
    'PORT=8252',
    'GIN_MODE=release',
    '',
    '# Media Library Configuration',
    `MEDIA_PATH=${config.mediaPaths.primary}`,
    `DOWNLOADS_PATH=${config.mediaPaths.downloads}`,
    `THUMBNAIL_PATH=/app/thumbnails`,
    '',
    '# API Keys',
    config.apiKeys.tmdb ? `TMDB_API_KEY=${config.apiKeys.tmdb}` : '# TMDB_API_KEY=your_tmdb_api_key_here',
    config.apiKeys.opensubtitles ? `OPENSUB_API_KEY=${config.apiKeys.opensubtitles}` : '# OPENSUB_API_KEY=your_opensubtitles_api_key',
    config.apiKeys.opensubtitlesUsername ? `OPENSUB_USERNAME=${config.apiKeys.opensubtitlesUsername}` : '# OPENSUB_USERNAME=your_username',
    config.apiKeys.opensubtitlesPassword ? `OPENSUB_PASSWORD=${config.apiKeys.opensubtitlesPassword}` : '# OPENSUB_PASSWORD=your_password',
    config.apiKeys.youtube ? `YOUTUBE_API_KEY=${config.apiKeys.youtube}` : '# YOUTUBE_API_KEY=your_youtube_api_key',
    '',
    '# Performance Configuration',
    `HW_ACCEL=${config.systemConfig.hardwareAcceleration}`,
    `CACHE_SIZE=${config.systemConfig.cacheSize}`,
    `CACHE_ENABLED=${config.systemConfig.enableRedis}`,
    `CHUNK_SIZE=1048576`,
    `LOG_LEVEL=info`,
    '',
    '# Redis Configuration',
    config.systemConfig.enableRedis ? 'REDIS_URL=redis://homeflix-redis:6379/0' : '# REDIS_URL=redis://localhost:6379/0',
    '',
    '# Torrent Configuration',
    config.systemConfig.enableTorrents ? 'JACKETT_URL=http://homeflix-jackett:9117' : '# JACKETT_URL=http://localhost:9117',
    config.systemConfig.enableTorrents ? '# JACKETT_API_KEY=your_jackett_api_key' : '# JACKETT_API_KEY=',
    '',
    '# Optional: Additional API Keys',
    '# GOOGLE_CLIENT_ID=your_google_client_id',
    '# GOOGLE_CLIENT_SECRET=your_google_client_secret',
    '# GEMINI_API_KEY=your_gemini_api_key',
    '# NEWS_API_KEY=your_news_api_key',
    ''
  ].join('\n');
  
  // Create frontend .env file
  const frontendEnvContent = [
    '# HomeFlix Frontend Configuration',
    '# Generated by Setup Wizard',
    '',
    '# API Configuration',
    'NEXT_PUBLIC_API_URL=http://localhost:8252',
    '',
    '# Environment',
    'NODE_ENV=production',
    'NEXT_TELEMETRY_DISABLED=1',
    '',
    '# Network Configuration',
    'PORT=3008',
    'HOSTNAME=0.0.0.0',
    ''
  ].join('\n');
  
  // Write backend .env
  await fs.writeFile('/app/config/backend.env', backendEnvContent);
  
  // Write frontend .env  
  await fs.writeFile('/app/config/frontend.env', frontendEnvContent);
  
  // Create main .env for docker-compose
  const dockerEnvContent = [
    '# HomeFlix Docker Configuration',
    '# Generated by Setup Wizard',
    '',
    '# Media Paths',
    `MEDIA_PATH=${config.mediaPaths.primary}`,
    `DOWNLOADS_PATH=${config.mediaPaths.downloads}`,
    '',
    '# API Keys',
    config.apiKeys.tmdb ? `TMDB_API_KEY=${config.apiKeys.tmdb}` : '# TMDB_API_KEY=',
    config.apiKeys.opensubtitles ? `OPENSUB_API_KEY=${config.apiKeys.opensubtitles}` : '# OPENSUB_API_KEY=',
    config.apiKeys.opensubtitlesUsername ? `OPENSUB_USERNAME=${config.apiKeys.opensubtitlesUsername}` : '# OPENSUB_USERNAME=',
    config.apiKeys.opensubtitlesPassword ? `OPENSUB_PASSWORD=${config.apiKeys.opensubtitlesPassword}` : '# OPENSUB_PASSWORD=',
    config.apiKeys.youtube ? `YOUTUBE_API_KEY=${config.apiKeys.youtube}` : '# YOUTUBE_API_KEY=',
    '',
    '# System Configuration',
    `HW_ACCEL=${config.systemConfig.hardwareAcceleration}`,
    config.systemConfig.enableTorrents ? 'JACKETT_URL=http://homeflix-jackett:9117' : '# JACKETT_URL=',
    config.systemConfig.enableTorrents ? '# JACKETT_API_KEY=' : '# JACKETT_API_KEY=',
    ''
  ].join('\n');
  
  await fs.writeFile('/app/config/.env', dockerEnvContent);
}

async function buildAndStartContainers(config: InstallRequest) {
  const profiles = ['production'];
  
  if (config.systemConfig.enableTorrents) {
    profiles.push('torrent');
  }
  
  // Build containers
  console.log('Building Docker containers...');
  await execAsync('docker-compose build', { cwd: '/app' });
  
  // Start containers with appropriate profiles
  console.log('Starting containers...');
  const profileArgs = profiles.map(p => `--profile ${p}`).join(' ');
  await execAsync(`docker-compose ${profileArgs} up -d`, { cwd: '/app' });
  
  // Wait for services to be ready
  console.log('Waiting for services to start...');
  await new Promise(resolve => setTimeout(resolve, 10000));
}

async function initializeDatabase(config: InstallRequest) {
  // The database will be automatically initialized by the backend service
  // We just need to wait for it to be ready and then configure it
  
  console.log('Initializing database...');
  
  // Wait for backend to be ready
  let retries = 30;
  while (retries > 0) {
    try {
      const response = await fetch('http://homeflix-backend:8252/api/health');
      if (response.ok) {
        break;
      }
    } catch (error) {
      // Service not ready yet
    }
    
    await new Promise(resolve => setTimeout(resolve, 2000));
    retries--;
  }
  
  if (retries === 0) {
    throw new Error('Backend service failed to start');
  }
  
  // Configure media paths
  for (const pathConfig of [
    { path: config.mediaPaths.primary, name: 'Primary Media Directory', type: 'primary' },
    { path: config.mediaPaths.downloads, name: 'Downloads Directory', type: 'downloads' },
    ...config.mediaPaths.additional.map((path, index) => ({
      path,
      name: `Additional Path ${index + 1}`,
      type: 'additional'
    }))
  ]) {
    try {
      await fetch('http://homeflix-backend:8252/api/admin/media-paths', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          path: pathConfig.path,
          name: pathConfig.name,
          path_type: pathConfig.type,
          is_active: true,
          priority: pathConfig.type === 'primary' ? 100 : pathConfig.type === 'downloads' ? 50 : 25
        }),
      });
    } catch (error) {
      console.error(`Failed to configure media path ${pathConfig.path}:`, error);
    }
  }
}

async function verifyInstallation() {
  console.log('Verifying installation...');
  
  // Check if all services are running
  const services = [
    { name: 'Backend', url: 'http://homeflix-backend:8252/api/health' },
    { name: 'Frontend', url: 'http://homeflix-frontend:3008' }
  ];
  
  for (const service of services) {
    try {
      const response = await fetch(service.url);
      if (!response.ok) {
        throw new Error(`${service.name} service is not responding correctly`);
      }
    } catch (error) {
      throw new Error(`${service.name} service verification failed: ${error}`);
    }
  }
  
  // Mark setup as complete
  const configPath = '/app/config/system.json';
  try {
    const systemConfig = JSON.parse(await fs.readFile(configPath, 'utf-8'));
    systemConfig.setupComplete = true;
    systemConfig.setupDate = new Date().toISOString();
    await fs.writeFile(configPath, JSON.stringify(systemConfig, null, 2));
  } catch (error) {
    console.error('Failed to mark setup as complete:', error);
  }
}